### ISSUE TITLE
Rust Tracing integration results in panic in application

### ISSUE THREAD

**Issue by hanishgogada** [getsentry/sentry-docs#10434] opened 2024-06-18 15:53 UTC
### Steps to Reproduce

1. Enabled `traces_sample_rate` in `ClientOptions`
2. Added tracing subscriber using 
     ``` 
     tracing_subscriber::registry()
    .with(tracing_subscriber::fmt::layer())
    .with(sentry_tracing::layer())
    .init();
     ```
3. Enabled tracing on rust methods through `#[tracing::instrument]`

### Expected Result

Expected to receive the traces in the console

### Actual Result

```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/util.rs:91:14
failed to set global default subscriber: SetLoggerError(())
```

### Additional Info

Http tracing through  sentry-actix is working fine. Wanted to enable tracing at the method level. 
I am sure this is bug in the docs, missing a step

**Comment by lizokm** [comment] 2024-07-10 15:59
@szokeasaurusrex Could you take a look at this issue and possibly help us resolve it?

**Comment by szokeasaurusrex** [comment] 2024-07-10 16:19
@lizokm, since this is a Rust SDK issue, @loewenheim or @Swatinem would likely know more about this than I do

**Comment by lizokm** [comment] 2024-07-10 16:52
Thanks @szokeasaurusrex! @loewenheim or @Swatinem if you could take a look, I would really appreciate it!

**Comment by Swatinem** [comment] 2024-07-11 07:06
A duplicate of this issue was also opened in the `sentry-rust` repo, which I answered and closed: https://github.com/getsentry/sentry-rust/issues/664#issuecomment-2184918953

**Closed by Swatinem** 2024-07-11 07:06 UTC
Labels: Bug, Platform: Rust, Waiting for: Support, Type: Content
