### ISSUE TITLE
Document side-effects of using Sentry alongside other tools (Crashlytics)

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry-docs#7017] opened 2023-05-25 11:15 UTC
### Core or SDK?

Platform/SDK

### Which part? Which one?

Android

### Description

There might be some side-effects/implicit behavior when using Sentry alongside other crash reporting tools like Crashlytics, especially when they are instantiated before ours and we don't have much time to process a crash.

### Suggested Solution

Document this

**Comment by kahest** [comment] 2024-07-15 09:19
duplicate of https://github.com/getsentry/sentry-docs/issues/4583

**Closed by kahest** 2024-07-15 09:19 UTC
Labels: Platform: Android, Team: Mobile Platform, Effort: Small, Impact: Medium, Type: Content
