### ISSUE TITLE
nit: Linebreak for pre-replaced code

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-docs#10401] opened 2024-06-14 11:26 UTC
### Steps to Reproduce

On https://docs.sentry.io/platforms/java/guides/spring-boot/
![image](https://github.com/getsentry/sentry-docs/assets/363802/ccf6fc00-e233-40d1-b93c-3697306e24b7)

The Line breaks probably because it's too long before the replaced value (just version) is inserted

### Expected Result

No line break

### Actual Result

line break

### Additional Info

https://github.com/getsentry/sentry-docs/blob/b356998095c645effe258074f4733c65004d19b7/platform-includes/getting-started-install/java.spring-boot.mdx#L17

**Comment by adinauer** [comment] 2024-06-14 12:02
Duplicate of https://github.com/getsentry/sentry-docs/issues/10252

**Closed by adinauer** 2024-06-14 12:02 UTC
Labels: Bug, Type: Platform
