### ISSUE TITLE
API - Crons (Beta) - Missing payload description for create-a-new-checkin and update-a-checkin

### ISSUE THREAD

**Issue by cbromberg** [getsentry/sentry-docs#6340] opened 2023-02-23 07:59 UTC
### Core or SDK?

Platform/SDK

### Which part? Which one?

API - Crons (Beta)

### Description

The documentation for the requests to https://docs.sentry.io/api/crons/create-a-new-checkin/ and https://docs.sentry.io/api/crons/update-a-checkin/ are missing the documentation for the JSON payload that needs to be sent - the curl examples also do not contain them.

I was only able to implement the health check finding the examples on the page

https://docs.sentry.io/product/crons/getting-started/?_ga=2.69696658.3612834.1677005378-103447541.1644998126#step-2-set-up-health-checks when switching to the "curl" view.

(Related: I already gave feedback that the creating and updating of the checkins could also be implemented as GET requests and only using the URL to transport different states - this would not allow to attach files or easily transport duration but would make it much easier to send that kind of data without dragging in a lot of complexity into the environment of the job (i.e. additional tooling like curl or a heavy SDK). 

### Suggested Solution

Include the payload description and examples :)

**Comment by gaprl** [comment] 2023-04-04 21:18
Hey there, thank you for your feedback. We're working on https://github.com/getsentry/sentry/issues/43666 to make our API docs, but in the meantime please use our updated Crons HTTP docs that includes additional details and examples of our check-in API: https://docs.sentry.io/product/crons/getting-started/http/#check-ins-recommended

Duplicate of https://github.com/getsentry/sentry/issues/43666

**Closed by gaprl** 2023-04-04 21:18 UTC
Labels: Status: Backlog, Team: Crons
