### ISSUE TITLE
Add Session Replay to project onboarding wizard

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-docs#6191] opened 2023-01-31 21:26 UTC
### Core or SDK?

Platform/SDK

### Which part? Which one?

JavaScript and all its integrations

### Description

When a new project of type JavaScript (or React, Angular, etc) is created, only errors and transactions are covered in the guide

### Suggested Solution

After the `# Verify` step, add "Add Session Replay".

This needs to be a clear 'optional' steps. With an explanation of what it does.
Point out that "this can be done later on the Replay menu" so users don't get hung up on this step and are able to move on without making a decision.

At the same time it should be simple to copy the additional lines of code and get it up and running.

**Comment by bruno-garcia** [comment] 2023-01-31 21:27
Set as `p2` because there's already an onboarding on the Replay index page with installation steps.
So even though users won't get Replay from with the initial set up process, it keeps that flow simpler.

**Comment by ryan953** [comment] 2023-02-01 16:28
duplicate of https://github.com/getsentry/sentry/issues/43502

**Closed by ryan953** 2023-02-01 16:28 UTC
Labels: Status: Backlog, Team: Emerging Technology
